- name: DEVELOPING CART APPLICATIPON
  hosts: cart
  become: yes

  tasks:
  - name: SETTING UP NODEJS
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

  - name: INSTALL NODEJS
    ansible.builtin.yum:
     name: nodejs 
     state: latest

  - name: CHECKING USER IS EXIST OR NOT
    ansible.builtin.command: id roboshop
    register: user
    ignore_errors: true

  - when: user.rc != 0
    name: create user roboshop
    become: yes 
    ansible.builtin.user:
      name: roboshop

  - name: CHECK WHETHER DIRECTORY IS EXIST OR NOT
    ansible.builtin.stat: 
      path: /app
    register: directory

  - when: directory.stat.exists == False
    name: create /app directory
    ansible.builtin.file:
      path: /app
      state: directory
    
  - name: DOWNLOADING THE APPLICATION
    ansible.builtin.get_url:
     url: https://roboshop-builds.s3.amazonaws.com/cart.zip
     dest: /tmp/cart.zip

  - name: UNZIPPING THE APPLICATION
    ansible.builtin.unarchive:
     src: /tmp/cart.zip
     dest: /app
     remote_src: yes

  - name: INSTALLING THE DEPENDENCIES
    ansible.builtin.command: npm install
    args:
     chdir: /app
    
  - name: DEAMON-RELOAD THE SERVICE
    ansible.builtin.systemd:
      daemon_reload: true

  - name: ENABLING AND STARTING THE SERVICE
    ansible.builtin.service:
     name: cart 
     state: started
     enabled: true

