- name: DEVELOPING CATALOGUE APPLICATION
  hosts: catalogue
  become: yes

  tasks:
  - name: SETUP NODEJS REPO
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

  - name: INSTALLING NODEJS APPLICATION
    ansible.builtin.yum:
     name: nodejs
     state: present

  - name: CHECKING WHETHER USER IS EXIST OR NOT
    ansible.builtin.command: id roboshop
    register: user
    ignore_errors: true
 
  - when: user.rc != 0
    name: CREATING USER
    become: yes
    ansible.builtin.user:
     name: roboshop

  - name: CHECKING WHETHER DIRECTORY EXISTS OR NOT
    ansible.builtin.stat:
     path: /app
    register: directory

  - name: PRINTING THE STAT OF THE FILE
    ansible.builtin.debug:
     msg: "output {{directory}}"

  - when: directory.stat.exists == False
    name: CREATING DIRECTORY
    ansible.builtin.file:
     path: /app
     state: directory

  - name: DOWNLOADING THE APPLICATION
    ansible.builtin.get_url:
     url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
     dest: /tmp/catalogue.zip 

  - name: UNZIPPING THE APPLICATION 
    ansible.builtin.unarchive:
     src: //tmp/catalogue.zip 
     dest: /app
     remote_src: yes

  - name: INSTALLING THE DEPENDENCIES
    ansible.builtin.command: npm install
    args:
     chdir: /app

  - name: COPYING FILES TO CATALOGUE SERVICE
    ansible.builtin.copy:
     src: catalogue.service
     dest: /etc/systemd/system/catalogue.service

  - name: DEAMON-RELOAD SERVICE
    ansible.builtin.systemd_service:
     daemon_reload: true

  - name: ENABLING AND STARTING THE SERVICE
    ansible.builtin.systemd_service:
     name: catalogue
     enabled: true

  - name: COPYING MONGO-DB REPO
    ansible.builtin.copy:
     src: mongodb.repo
     dest: /etc/yum.repos.d/mongo.repo
     remote_src: yes


  - name: INSTALLING MONGO-REPO SHELL
    ansible.builtin.yum:
     name: mongodb-org-shell
     state: present
    
  - name: LOADING THE SHCEMA
    ansible.builtin.command: mongo --host 172.31.24.34 < /app/schema/catalogue.js
     
     




  