- name: DEVELOPING CATALOGUE APPLICATION
  hosts: catalogue
  become: yes

  tasks:
  - name: SETUP NODEJS REPO
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

  - name: INSTALLING NODEJS APPLICATION
    ansible.builtin.yum:
     name: nodejs
     state: present

  - name: CHECKING WHETHER USER IS EXIST OR NOT
    ansible.builtin.yum: id roboshop
     register: user
     