- name: DEVELOPING CATALOGUE APPLICATION
  hosts: catalogue
  become: yes

  tasks:
  - name: SETUP NODEJS REPO
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

  - name: INSTALLING NODEJS APPLICATION
    ansible.builtin.yum:
     name: nodejs
     state: present

  - name: CHECKING WHETHER USER IS EXIST OR NOT
    ansible.builtin.command: id roboshop
    register: user
    ignore_errors: true
 
  - when: user.rc != 0
    name: CREATING USER
    become: yes
    ansible.builtin.user:
     name: roboshop

  - name: CHECKING WHETHER DIRECTORY EXISTS OR NOT
    ansible.builtin.stat:
    path: /app
    register: directory

  