- name: DEVELOPING RABBITMQ SOFTWARE
  hosts: rabbitmq
  become: yes

  tasks: 

  - name: CONFIGURING YUM REPO
    ansible.builtin.shell: "{{ item }}"
    loop:
     - curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
     - curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

  - name: INSATLLING RANBBITMQ SERVER
    ansible.builtin.yum:
     name:  rabbitmq-server
     state: latest

  - name: ENABLING AND STARTING THE SERVICE
    ansible.builtin.service:
     name: rabbitmq-server 
     state: started
     enabled: true

  - name: CREATING USER FOR APPLICATION
    ansible.builtin.shell:  rabbitmqctl add_user roboshop roboshop123

  - name: SETTING UP PERMISSIONS
    ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
