- name: DEVELOPING USER APPLICATION
  hosts: user
  become: yes

  tasks:
  - name: SETTING UP NODEJS REPO
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

  - name: INSTALL NODEJS APPLICATION
    ansible.builtin.yum:
     name: nodejs
     state: latest

  - name: CHECKING USER IS EXITS OR NOT
    ansible.builtin.command: id roboshop
    register: user
    ignore_errors: true

  - when: user.rc !=0
    name: CREATING USER
    ansible.builtin.user:
    become: yes
     name: roboshop

  - name: CHECKING DIRECTORY EXIST OR NOT
    ansible.builtin.stat:
     path: /app
     register: directory

  - when: directory.stat.exists == False
    name: PRINTING DIRECTORY EXISTS OR NOT
    ansible.builtin.file:
     path: /app
     state: directory

  - name: DOWNLOADING THE APPLICATION
    ansible.builtin.get_url:
     url:  https://roboshop-builds.s3.amazonaws.com/user.zip
     dest: /tmp/user.zip

  - name: UNZIPPING THE APPLICATION
    ansible.builtin.unarchive:
     src: /tmp/user.zip
     dest: /app

  - name: INSTALLING THE DEPENDENCIES
    ansible.builtin.command: npm install
    args:
     chdir: /app

  - name: COPYING USER SERVICE
    ansible.builtin.copy:
     src: user.service
     dest: /etc/systemd/system/user.service

  - name: DEAMON RELOADING
    ansible.builtin.systemd:
      daemon_reload: true

  - name: ENABLING AND STARTING THE SERVICE
    ansible.builtin.service:
     name: user 
     state: started
     enabled: true

  - name: COPYING MONGO-REPO
    ansible.builtin.copy:
     src: mongodb.repo
     dest: /etc/yum.repos.d/mongodb.repo

  - name: INSTALL MONGODB-SHELL APPLICATION
    ansible.builtin.yum:
     name: mongodb-org-shell
     state: latest

  - name: LOADING THE SCHEMAN
    ansible.builtin.command: mongo --host 172.31.24.34 </app/schema/user.js

  - name: RESTARTING THE SERVICE
    ansible.builtin.service:
     name: user 
     state: restarted
     


    
    

    